# Generated by desktop_suite_packager.py; source=packaging/desktop-suite.toml; sha256=9c450358c979f7fbe4cd2cf3560b01346123258fda483d1b7c2d07daedf6f4b8
[CmdletBinding()]
    param(
        [switch]$UnsignedDevelopmentBuild,
        [switch]$SkipTests,
        [switch]$SkipInstaller
    )

    $ErrorActionPreference = 'Stop'
    Set-StrictMode -Version Latest
    $projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
    $manifest = Join-Path $projectRoot 'packaging\desktop-suite.toml'
    $expectedManifestHash = '9C450358C979F7FBE4CD2CF3560B01346123258FDA483D1B7C2D07DAEDF6F4B8'
    $actualManifestHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $manifest).Hash
    if ($actualManifestHash -ne $expectedManifestHash) {
        throw 'desktop-suite.toml changed. Regenerate packaging files before building.'
    }

    function Assert-Path([string]$Path) {
        if (-not (Test-Path -LiteralPath $Path)) { throw "Required bundle path is missing: $Path" }
    }

    function Assert-File([string]$Path) {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Required bundle file is missing: $Path" }
    }

    function Find-SignTool {
        $command = Get-Command 'signtool.exe' -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
        return $null
    }

    function Sign-Artifact([string]$Path, [string]$SignTool) {
        & $SignTool sign /sha1 $env:WINDOWS_CERT_SHA1 /fd SHA256 /tr $env:WINDOWS_TIMESTAMP_URL /td SHA256 $Path
        if ($LASTEXITCODE -ne 0) { throw "Signing failed: $Path" }
        & $SignTool verify /pa $Path
        if ($LASTEXITCODE -ne 0) { throw "Signature verification failed: $Path" }
    }

    Push-Location $projectRoot
    try {
        if (-not (Get-Command 'uv' -ErrorAction SilentlyContinue)) { throw 'uv is required for locked release builds.' }
        & 'uv' 'sync' '--locked' '--extra' 'suite' '--extra' 'test' '--group' 'desktop-build'
        if ($LASTEXITCODE -ne 0) { throw 'uv sync failed.' }

        if (-not $SkipTests) {
        Write-Host 'Quality command 1: uv run --locked python -m pytest'
& 'uv' 'run' '--locked' 'python' '-m' 'pytest'
if ($LASTEXITCODE -ne 0) { throw 'Quality command 1 failed.' }
        }

        $distDir = Join-Path $projectRoot 'release'
        $stageDir = Join-Path $distDir 'stage'
        $workDir = Join-Path $projectRoot 'build\desktop-suite'
        if (Test-Path -LiteralPath $stageDir) { Remove-Item -LiteralPath $stageDir -Recurse -Force }
        if (Test-Path -LiteralPath $workDir) { Remove-Item -LiteralPath $workDir -Recurse -Force }
        New-Item -ItemType Directory -Force -Path $distDir | Out-Null

        & 'uv' 'run' '--locked' 'python' '-m' 'PyInstaller' (Join-Path $projectRoot 'packaging\generated\chwezi-document-suite.spec') '--noconfirm' '--clean' '--distpath' $stageDir '--workpath' $workDir
        if ($LASTEXITCODE -ne 0) { throw 'PyInstaller build failed.' }

        $suiteDir = Join-Path $stageDir 'chwezi-document-suite'
        Assert-Path $suiteDir
        Assert-File (Join-Path $suiteDir 'ChweziDocumentSuite.exe')
Assert-File (Join-Path $suiteDir 'ChweziOrganizer.exe')
Assert-File (Join-Path $suiteDir 'ChweziSigner.exe')
Assert-File (Join-Path $suiteDir 'ChweziMarkdown.exe')
        Assert-Path (Join-Path (Join-Path $suiteDir '_internal') 'templates')
Assert-Path (Join-Path (Join-Path $suiteDir '_internal') 'static')
Assert-Path (Join-Path (Join-Path $suiteDir '_internal') '.')

        $smokeResults = @()
        $smokeResults += [ordered]@{ application = 'interactive-applications'; result = 'manual-check-required'; exit_code = $null }

        $signingRequired = $true
        $signed = $false
        if ($signingRequired -and -not $UnsignedDevelopmentBuild) {
            if (-not $env:WINDOWS_CERT_SHA1 -or -not $env:WINDOWS_TIMESTAMP_URL) {
                throw 'Signing is required. Set WINDOWS_CERT_SHA1 and WINDOWS_TIMESTAMP_URL.'
            }
            $signTool = Find-SignTool
            if (-not $signTool) { throw 'signtool.exe was not found.' }
            Get-ChildItem -LiteralPath $suiteDir -Filter '*.exe' -File | ForEach-Object { Sign-Artifact $_.FullName $signTool }
            $signed = $true
        } elseif ($signingRequired) {
            Write-Warning 'Unsigned development build: do not publish these artifacts.'
        }

        if ($true) {
            $zipPath = Join-Path $distDir 'chwezi-document-suite-0.2.0-windows-x64.zip'
            if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
            Compress-Archive -Path (Join-Path $suiteDir '*') -DestinationPath $zipPath -CompressionLevel Optimal
        }

        $installerPath = $null
        if ($true -and -not $SkipInstaller) {
            $isccCommand = Get-Command 'ISCC.exe' -ErrorAction SilentlyContinue
            $iscc = if ($isccCommand) { $isccCommand.Source } else { $null }
            if (-not $iscc) {
                $candidates = @(
                    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
                    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
                    "$env:ProgramFiles\Inno Setup 7\ISCC.exe"
                )
                $iscc = $candidates | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
            }
            if (-not $iscc) { throw 'Inno Setup compiler ISCC.exe was not found.' }
            & $iscc (Join-Path $projectRoot 'packaging\generated\chwezi-document-suite.iss')
            if ($LASTEXITCODE -ne 0) { throw 'Inno Setup compilation failed.' }
            $installerPath = Join-Path $distDir 'chwezi-document-suite-Setup-0.2.0.exe'
            Assert-File $installerPath
            if ($signingRequired -and -not $UnsignedDevelopmentBuild) { Sign-Artifact $installerPath $signTool }
        }

        $artifactRows = Get-ChildItem -LiteralPath $distDir -File | ForEach-Object {
            [ordered]@{ name = $_.Name; bytes = $_.Length; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant() }
        }
        $evidence = [ordered]@{
            schema_version = 1
            product = 'Chwezi Document Suite'
            version = '0.2.0'
            manifest_sha256 = $actualManifestHash.ToLowerInvariant()
            generated_utc = [DateTime]::UtcNow.ToString('o')
            python = (& 'uv' 'run' '--locked' 'python' '--version' 2>&1 | Out-String).Trim()
            pyinstaller = (& 'uv' 'run' '--locked' 'python' '-m' 'PyInstaller' '--version' 2>&1 | Out-String).Trim()
            signed = $signed
            unsigned_development_build = [bool]$UnsignedDevelopmentBuild
            smoke = $smokeResults
            artifacts = @($artifactRows)
        }
        $evidence | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $distDir 'desktop-suite-evidence.json') -Encoding utf8
        Write-Host "Desktop suite build completed: $distDir"
    } finally {
        Pop-Location
    }
